### ISSUE TITLE
Upgrade & Revise Sample Applications

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp-samples#209]
We currently have a lot of samples here: https://github.com/abpframework/abp-samples
And it will be more by the time. Some of these applications are mentioned in the documentation, some of the are source code of the projects explained in ABP Community articles.

We should better organize these samples.

We don't need to upgrade all of these in every release. This would be a huge work. However, we may upgrade them in every major release (6.0, 7.0, 8.0, etc.), especially the ones officially documented and maintained.

- [x] Upgrade samples to ABP 7.0 final (after it is released) @realLiangshiwei  https://github.com/abpframework/abp-samples/pull/220
- [x] Add a README.md file to the root folder of each sample. Explain the sample in a few sentences. For community articles, link to the article ([example](https://github.com/abpframework/abp-samples/tree/master/EfCoreEntityDependencyInjectionDemo)). For the sample explain on documentation, explain and give the related link (for example, [this sample](https://github.com/abpframework/abp-samples/tree/master/BookStore-Mvc-EfCore) should have a reference to the [bookstore tutorial](https://docs.abp.io/en/abp/latest/Tutorials/Part-1?UI=MVC&DB=EF)). For others, please write an explanation and add related links if available. @realLiangshiwei  https://github.com/abpframework/abp-samples/pull/217

<del>I assigned this to multiple people. @maliming please organize this and split the samples between people. Then, after ABP 7.0 final release, you all start the work.</del>

**Comment by realLiangshiwei** [comment]
Angular UI:

- [ ] [AcmeBookStoreAngularMaterial](https://github.com/abpframework/abp-samples/tree/liangshiwei/abp7.0/AcmeBookStoreAngularMaterial/angular)
- [ ] [CustomAngularAppWithIdentityServer](https://github.com/abpframework/abp-samples/tree/liangshiwei/abp7.0/CustomAngularAppWithIdentityServer)
- [ ] [DevExtreme-Angular](https://github.com/abpframework/abp-samples/tree/liangshiwei/abp7.0/DevExtreme-Angular)
- [ ] [NG-TIERED](https://github.com/abpframework/abp-samples/tree/liangshiwei/abp7.0/DomainTenantResolver/NG-TIERED)
- [ ] [DomainTenantResolver NG](https://github.com/abpframework/abp-samples/tree/liangshiwei/abp7.0/DomainTenantResolver/NG/)
- [ ] [DomainTenantResolver NG](https://github.com/abpframework/abp-samples/tree/liangshiwei/abp7.0/DomainTenantResolver/OpenIddict/NG)
- [ ] [IdentityServerReferenceToken](https://github.com/abpframework/abp-samples/tree/liangshiwei/abp7.0/IdentityServerReferenceToken)
- [ ] [PrimengSample](https://github.com/abpframework/abp-samples/tree/liangshiwei/abp7.0/PrimengSample)
