### ISSUE TITLE
AbpException: Could not find the bundle file '/libs/abp/core/abp.css' for the bundle 'LeptonXLite.Global'!

### ISSUE THREAD

**Issue by 96068chandra** [abpframework/abp-samples#227]
When I was clicking on login button I'm getting error like. I have installed all the libraries through the command abp install-libs but I'm getting this error
![Screenshot (315)](https://user-images.githubusercontent.com/87321782/224935808-4a6fbad9-7cdb-405c-9ceb-43e40a4ae4ea.png)
![Screenshot (316)](https://user-images.githubusercontent.com/87321782/224935820-5328dd7f-87d3-41be-845e-09a287371edb.png)

**Comment by maliming** [comment]
hi

You can try to run `abp install-libs` command on the root folder of your project.

**Comment by TRB7** [comment]
Had same issue and tried @maliming 's recommandation "abp install-libs" and it worked fine
