### ISSUE TITLE
 Unable to find package Volo.Abp.Identity.Domain.Shared with version (>= 7.1.0)

### ISSUE THREAD

**Issue by 96068chandra** [abpframework/abp-samples#231]
When I was creating new web assembly solution I'm getting error like this **" Unable to find package Volo.Abp.Identity.Domain.Shared with version (>= 7.1.0)"**
![Screenshot (320)](https://user-images.githubusercontent.com/87321782/226678274-0812cc19-ba02-4918-8b77-8519d400377c.png)
![Screenshot (321)](https://user-images.githubusercontent.com/87321782/226678291-4eabe38e-a111-4753-91f5-ebc0f8a124a7.png)

**Comment by realLiangshiwei** [comment]
7.1.0 is still being released

**Comment by 96068chandra** [comment]
How to resolve this error

**Comment by realLiangshiwei** [comment]
You can use the `version` option.
`abp new project --version 7.0.3`

**Comment by 96068chandra** [comment]
Thankyou @realLiangshiwei. It is resolved
