### ISSUE TITLE
I deployed a template project on IIS and found that all PUT and DELETE methods return 302

### ISSUE THREAD

**Issue by zhouguangxxx** [abpframework/abp-samples#238]
I deployed the BookStore-Mvc-EfCore project on IIS.At first, all the put and delete api returned 405, so I removed WebDav. However, after that, the put and delete interfaces returned 302. What should I do
![1680783982629](https://user-images.githubusercontent.com/22882146/230382424-b9400efc-5159-4905-b7bc-d28447dabbb0.png)
![1680784047635](https://user-images.githubusercontent.com/22882146/230382475-05a4e3f9-2fc7-48e2-a217-1c7d8f51b590.png)
![微信截图_20230406204656](https://user-images.githubusercontent.com/22882146/230382888-fb01aa06-6401-467a-a332-d38c9eba165d.png)

**Comment by maliming** [comment]
Please check your **logs.txt**.

**Comment by zhouguangxxx** [comment]
I check my log and found this message:
Antiforgery token validation failed. The required antiforgery header value "RequestVerificationToken" is not present.
Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The required antiforgery header value "RequestVerificationToken" is not present.
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.ValidateRequestAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.ValidateAntiforgeryTokenAuthorizationFilter.OnAuthorizationAsync(AuthorizationFilterContext context)

then i removed anti forgery token check,it worked
```
context.Services.AddRazorPages(options =>
        {
            options.Conventions.ConfigureFilter(new IgnoreAntiforgeryTokenAttribute());
        });
 Configure<AbpAntiForgeryOptions>(options =>
        {
            options.AutoValidate = false;
        });
```
But how could I get the front-end to pass in the correct token?

**Comment by maliming** [comment]
You can try to use `https` for your iis site.
