### ISSUE TITLE
PluginSample proyect not works

### ISSUE THREAD

**Issue by washyn** [abpframework/abp-samples#239]
I was trying to create a plugin, for which I reviewed the sample application, but when trying to run the example it shows me the following error screen.
![image](https://user-images.githubusercontent.com/15305896/231927921-0126dc9d-b9c8-475c-bdff-1a583d5a1838.png)

**Comment by maliming** [comment]
hi

Please share the file info in the `PluginSample` directory.

`Path.Combine(parentDirectory.FullName, "MyPlugIn", "bin", "Debug", "net7.0");`

**Comment by washyn** [comment]
![image](https://user-images.githubusercontent.com/15305896/231931385-5f31363a-906e-4bb0-821f-524beb716045.png)
I am running the same sample project "PlugInSample", this without making changes

**Comment by maliming** [comment]
hi

Please try to remove the `refs` folder or `myplugin.deps.json`

**Comment by washyn** [comment]
Thank you very much, I removed the file "myplugin.deps.json" it works now, I think this detail should be added in the documentation https://docs.abp.io/en/abp/latest/PlugIn-Modules

**Comment by maliming** [comment]
https://github.com/abpframework/abp/pull/16266
