### ISSUE TITLE
How is a self-signed certificate generated

### ISSUE THREAD

**Issue by lee-vic** [abpframework/abp-samples#241]
An example of multi-tenancy.
I know this is not related to the apb framework, I tried to generate my own self-signed certificate, but only support level 1 wildcards. The domain name certificate tenant1.web.mytest.com is invalid. Could you tell me how to generate the certificate?

**Comment by maliming** [comment]
We was use https://letsencrypt.org/

**Comment by lee-vic** [comment]
Thanks!I'll try!
