### ISSUE TITLE
Sample Code not upgraded to 8.0

### ISSUE THREAD

**Issue by brauerj-gc** [abpframework/abp-samples#267]
Sample Code not upgraded to 8.0

**Comment by brauerj-gc** [comment]
Also where is a cms kit sample?

**Comment by EngincanV** [comment]
> Also where is a cms kit sample?

You can check the [CMS Kit Demo repository](https://github.com/abpframework/cms-kit-demo).

**Comment by EngincanV** [comment]
We can update the sample projects to v8.0.0. You can use the `abp update` command (https://docs.abp.io/en/abp/latest/CLI#update) to update the samples and then you should run each sample application and test them to see if they are working properly. 

Also please check [the migration guide](https://docs.abp.io/en/abp/latest/Migration-Guides/Index) and check if any action is required while upgrading the samples. If you have any problem or any additional steps to take, please write to me, so I can update the migration guides or create an issue.

Here are the samples that we need to update:

* Tutorials (all bookstore samples)
   * [BookStore-Angular-MongoDb](https://github.com/abpframework/abp-samples/tree/master/BookStore-Angular-MongoDb)
   * [BookStore-Blazor-EfCore](https://github.com/abpframework/abp-samples/tree/master/BookStore-Blazor-EfCore)
   * [BookStore-Modular](https://github.com/abpframework/abp-samples/tree/master/BookStore-Modular)
   * [BookStore-Mvc-EfCore](https://github.com/abpframework/abp-samples/tree/master/BookStore-Mvc-EfCore) - it seems it's already done: https://github.com/abpframework/abp-samples/pull/263
* Quick Start (Todo Applications)
  * [TodoApp-SingleLayer](https://github.com/abpframework/abp-samples/tree/master/TodoApp-SingleLayer)
  * [TodoApp](https://github.com/abpframework/abp-samples/tree/master/TodoApp)
