### ISSUE TITLE
[BookStore-Mvc-EfCore] BookStore/Books： BookType Localization didn't realize like the document

### ISSUE THREAD

**Issue by cy-jing** [abpframework/abp-samples#269]
I can run this sample successfully,and didn‘t change anything ,but this part didn't implement as I expected
![screenShot](https://github.com/abpframework/abp-samples/assets/149367721/9afd0b80-9833-4747-88b8-4a2e3410840a)
![image](https://github.com/abpframework/abp-samples/assets/149367721/17446b79-7eb2-49fb-ac4c-a05b09712d38)

**Comment by maliming** [comment]
I tested in `master` branch and it looks like:

<img width="2121" alt="image" src="https://github.com/abpframework/abp-samples/assets/6908465/b301c2ad-570c-41ae-938a-5860b5fe1c73">

**Comment by cy-jing** [comment]
sorry,i didn't add localization in zh-Hans.json, but there is another question:

this is the sample on the document 
![image](https://github.com/abpframework/abp-samples/assets/149367721/8f8f1c99-0184-48f2-afcd-47a0590e7724)
![image](https://github.com/abpframework/abp-samples/assets/149367721/425ce3b7-9ed3-4363-b90c-ab6689c7e3c3)


this is the sample i pull from git
![image](https://github.com/abpframework/abp-samples/assets/149367721/c0525d8a-7781-4fc9-bb5e-1fb9b32b3751)
i tried to realize localization like the document, but failed

**Comment by maliming** [comment]
The Chinese documentation may not be up to date. Please refer to the English documentation.

**Comment by cy-jing** [comment]
Ok, thanks for the answer
